'use client'

import Image from 'next/image'
import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, ChevronDown, Minus, Plus, ShoppingBag, X } from 'lucide-react'

type Product = { id: string; name: string; description: string; price: number; image?: string; category: string }
type CartItem = Product & { quantity: number }
type Option = { name: string; extra: number }

const sizes: Option[] = [{ name: '300 ml', extra: 14.9 }, { name: '500 ml', extra: 18.9 }, { name: '700 ml', extra: 22.9 }]
const fruits: Option[] = ['Banana', 'Morango', 'Kiwi'].map(name => ({ name, extra: 0 }))
const toppings: Option[] = ['Granola', 'Paçoca', 'Leite em pó', 'Gotas de chocolate'].map(name => ({ name, extra: 1.5 }))
const creams: Option[] = ['Creme de Ninho', 'Creme de paçoca', 'Creme de chocolate'].map(name => ({ name, extra: 2.5 }))
const featured: Product[] = [
  { id: 'classico', name: 'Clássico 53', description: 'Açaí, banana, morango, granola e leite em pó.', price: 19.9, image: '/images/acai-bowl.png', category: 'Açaí' },
  { id: 'ninho', name: 'Ninho & Morango', description: 'Açaí, creme de Ninho, morango e leite em pó.', price: 22.9, image: '/images/acai-closeup.png', category: 'Açaí' },
  { id: 'pacoca', name: 'Paçoca Crunch', description: 'Açaí, creme de paçoca, banana e granola.', price: 21.9, image: '/images/acai-hero.png', category: 'Açaí' },
]
const combos: Product[] = [
  { id: 'duo', name: 'Combo Duo', description: '2 açaís 500 ml', price: 35.9, image: '/images/acai-bowl.png', category: 'Combos' },
  { id: 'combo53', name: 'Combo 53', description: 'Açaí 500 ml + bebida', price: 23.9, image: '/images/acai-closeup.png', category: 'Combos' },
]
const drinks: Product[] = [
  { id: 'agua', name: 'Água mineral', description: 'Com ou sem gás.', price: 4.9, category: 'Bebidas' },
  { id: 'mate', name: 'Mate gelado', description: 'Mate natural, 300 ml.', price: 7.9, category: 'Bebidas' },
]
const money = (value: number) => `R$ ${value.toFixed(2).replace('.', ',')}`

export default function Page() {
  const [cart, setCart] = useState<CartItem[]>([])
  const [drawer, setDrawer] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [size, setSize] = useState(sizes[1])
  const [selected, setSelected] = useState<Option[]>([])
  const [category, setCategory] = useState('Açaí')
  const [showMobileBar, setShowMobileBar] = useState(false)
  const customPrice = size.extra + selected.reduce((sum, item) => sum + item.extra, 0)
  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0)
  const cartTotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const menu = [...featured, ...combos, ...drinks]
  const visibleMenu = useMemo(() => menu.filter(item => item.category === category), [category])

  useEffect(() => {
    const onScroll = () => setShowMobileBar(window.scrollY > 420)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const addToCart = (product: Product) => setCart(current => {
    const found = current.find(item => item.id === product.id)
    return found ? current.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }]
  })
  const addCustom = () => addToCart({ id: `custom-${size.name}-${selected.map(item => item.name).join('-')}`, name: `Açaí ${size.name}`, description: selected.length ? selected.map(item => item.name).join(', ') : 'Açaí puro', price: customPrice, category: 'Açaí' })
  const changeQuantity = (id: string, amount: number) => setCart(current => current.flatMap(item => item.id === id ? (item.quantity + amount > 0 ? [{ ...item, quantity: item.quantity + amount }] : []) : [item]))
  const toggleOption = (option: Option) => setSelected(current => current.some(item => item.name === option.name) ? current.filter(item => item.name !== option.name) : [...current, option])

  return <main className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-primary/10 bg-background/95 backdrop-blur-sm"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 lg:px-10 lg:py-4"><a href="#top" aria-label="ROXO 53 início" className="leading-none"><span className="font-display text-xl font-bold">ROXO 53</span><span className="mt-1 block font-mono text-[9px] tracking-[.24em] text-primary/60">AÇAÍ & BOWLS</span></a><nav className="hidden gap-8 text-[11px] font-bold uppercase tracking-[.14em] lg:flex"><a href="#pedidos">Escolhe o teu</a><a href="#monte">Monte o teu</a><a href="#cardapio">Cardápio</a><a href="#local">Onde encontrar</a></nav><div className="flex items-center gap-2"><button onClick={() => setDrawer(true)} className="relative flex min-h-11 items-center gap-2 bg-primary px-4 text-xs font-bold uppercase tracking-wider text-primary-foreground"><ShoppingBag size={16}/> Pedir{totalItems > 0 && <span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-accent text-[10px] text-primary">{totalItems}</span>}</button><button onClick={() => setMenuOpen(!menuOpen)} className="flex min-h-11 w-11 items-center justify-center border border-primary/20 lg:hidden" aria-label="Abrir menu">{menuOpen ? <X size={18}/> : <span className="space-y-1"><i className="block h-px w-4 bg-current"/><i className="block h-px w-4 bg-current"/></span>}</button></div></div>{menuOpen && <nav className="border-t border-primary/10 px-5 py-4 lg:hidden"><div className="flex flex-col gap-4 text-xs font-bold uppercase tracking-wider"><a href="#pedidos" onClick={() => setMenuOpen(false)}>Escolhe o teu</a><a href="#monte" onClick={() => setMenuOpen(false)}>Monte o teu</a><a href="#cardapio" onClick={() => setMenuOpen(false)}>Cardápio</a><a href="#local" onClick={() => setMenuOpen(false)}>Onde encontrar</a></div></nav>}</header>

    <section id="top" className="mx-auto grid max-w-7xl gap-6 px-5 pb-12 pt-5 md:grid-cols-[1fr_.9fr] md:gap-10 md:px-10 md:pb-24 md:pt-20"><div className="order-2 flex flex-col justify-center md:order-1"><p className="mb-4 font-mono text-[10px] font-bold uppercase tracking-[.3em] text-berry">Feito na hora · Pelotas, RS</p><h1 className="max-w-xl font-display text-[clamp(3.2rem,13vw,8rem)] font-bold leading-[.83] tracking-[-.07em]">DO TEU<br/><span className="text-berry">JEITO.</span><br/>ATÉ A ÚLTIMA<br/>COLHERADA.</h1><div className="mt-6 flex flex-wrap gap-3"><a href="#monte" className="inline-flex min-h-12 items-center gap-3 bg-primary px-5 text-xs font-bold uppercase tracking-wider text-primary-foreground">Montar meu açaí <ArrowDown size={15}/></a><a href="#cardapio" className="inline-flex min-h-12 items-center border border-primary/25 px-5 text-xs font-bold uppercase tracking-wider">Ver cardápio</a></div></div><div className="order-1 relative mx-auto w-full max-w-md md:order-2"><div className="relative aspect-[1.08] overflow-hidden bg-accent md:aspect-[.84]"><Image src="/images/acai-hero.png" alt="Copo de açaí com frutas e granola" fill priority className="object-cover" sizes="(max-width: 768px) 92vw, 42vw"/></div><div className="absolute -bottom-3 -left-3 bg-berry px-4 py-3 font-display text-base font-bold text-primary-foreground">feito do teu jeito<span className="ml-2 text-accent">*</span></div></div></section>

    <section id="pedidos" className="bg-primary px-5 py-14 text-primary-foreground md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><div className="mb-9"><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-accent">01 · favoritos da casa</p><h2 className="max-w-lg font-display text-5xl font-bold leading-[.88] tracking-[-.06em] md:text-7xl">ESCOLHE<br/><span className="text-accent">O TEU.</span></h2></div><div className="grid gap-9 md:grid-cols-3 md:gap-6">{featured.map((item, index) => <article key={item.id} className={index === 1 ? 'md:mt-16' : ''}><button onClick={() => addToCart(item)} className="group block w-full text-left"><div className="relative aspect-[1.08] overflow-hidden bg-cream"><Image src={item.image!} alt={item.name} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="(max-width: 768px) 92vw, 30vw"/></div><div className="flex items-start justify-between gap-3 pt-4"><div><h3 className="font-display text-2xl font-bold uppercase">{item.name}</h3><p className="mt-1 max-w-xs text-sm leading-relaxed text-primary-foreground/65">{item.description}</p></div><span className="whitespace-nowrap font-mono text-sm text-accent">{money(item.price)}</span></div></button></article>)}</div></div></section>

    <section className="bg-cream px-5 py-14 md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><div className="mb-9 flex items-end justify-between"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-berry">02 · pra compartilhar</p><h2 className="font-display text-5xl font-bold leading-[.88] tracking-[-.06em] text-primary md:text-7xl">PRA DIVIDIR.<br/><span className="text-berry">OU NÃO.</span></h2></div><ArrowUpRight className="hidden text-berry md:block" size={36}/></div><div className="grid gap-5 md:grid-cols-[1.2fr_.8fr] md:items-end"><ComboCard product={combos[0]} onAdd={() => addToCart(combos[0])} large/><ComboCard product={combos[1]} onAdd={() => addToCart(combos[1])}/></div></div></section>

    <section id="monte" className="bg-background px-5 py-14 md:px-10 md:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-4 font-mono text-[10px] font-bold uppercase tracking-[.3em] text-berry">03 · personaliza</p><h2 className="font-display text-6xl font-bold leading-[.86] tracking-[-.07em] text-primary md:text-8xl">MONTE<br/>O TEU.</h2><p className="mt-6 max-w-xs text-sm leading-relaxed text-primary/65">O bowl começa com a tua escolha. O resto é por nossa conta.</p></div><div className="space-y-8"><OptionGroup title="Escolhe o tamanho" step="01"><div className="grid grid-cols-3 gap-2">{sizes.map(item => <button key={item.name} onClick={() => setSize(item)} className={`border p-3 text-left ${size.name === item.name ? 'border-primary bg-primary text-primary-foreground' : 'border-primary/20'}`}><span className="block font-display text-lg font-bold">{item.name}</span><span className="mt-1 block font-mono text-xs">{money(item.extra)}</span></button>)}</div></OptionGroup><OptionGroup title="Escolhe as frutas" step="02"><ChoiceList items={fruits} selected={selected} toggle={toggleOption}/></OptionGroup><OptionGroup title="Vai um complemento?" step="03"><ChoiceList items={toppings} selected={selected} toggle={toggleOption}/></OptionGroup><OptionGroup title="Finaliza com creme" step="04"><ChoiceList items={creams} selected={selected} toggle={toggleOption}/></OptionGroup><div className="border-t border-primary/15 pt-5"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-primary/55">Seu açaí</p><div className="mt-2 flex max-w-xs flex-wrap gap-1.5">{selected.length ? selected.map(item => <span key={item.name} className="bg-primary/8 px-2 py-1 text-xs text-primary">{item.name}</span>) : <span className="text-sm text-primary/55">Escolha seus ingredientes</span>}</div></div><strong className="font-display text-3xl text-primary">{money(customPrice)}</strong></div><button onClick={addCustom} className="mt-5 flex min-h-13 w-full items-center justify-center gap-3 bg-primary px-5 text-xs font-bold uppercase tracking-wider text-primary-foreground">Adicionar ao pedido <Plus size={16}/></button></div></div></div></section>

    <section className="relative min-h-[42vh] overflow-hidden bg-primary md:min-h-[58vh]"><Image src="/images/acai-closeup.png" alt="Camadas de açaí, creme e frutas" fill className="object-cover opacity-75" sizes="100vw"/><div className="absolute inset-0 bg-primary/25"/><div className="relative flex min-h-[42vh] items-end px-5 py-9 md:min-h-[58vh] md:px-10 md:py-16"><h2 className="font-display text-7xl font-bold leading-[.82] tracking-[-.07em] text-cream md:text-[10rem]">CAMADA<br/>POR<br/><span className="text-accent">CAMADA.</span></h2></div></section>

    <section id="cardapio" className="px-5 py-14 md:px-10 md:py-24"><div className="mx-auto max-w-5xl"><div className="mb-9 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-berry">04 · cardápio</p><h2 className="font-display text-6xl font-bold leading-[.86] tracking-[-.07em]">ESCOLHE<br/>E PEDE.</h2></div><div className="flex border-b border-primary/20">{['Açaí', 'Combos', 'Bebidas'].map(item => <button key={item} onClick={() => setCategory(item)} className={`px-3 py-3 text-xs font-bold uppercase tracking-wider ${category === item ? 'border-b-2 border-berry text-berry' : 'text-primary/45'}`}>{item}</button>)}</div></div><div className="divide-y divide-primary/15 border-y border-primary/15">{visibleMenu.map((item, index) => <div key={item.id} className="flex items-center justify-between gap-4 py-5"><div className="flex items-start gap-4"><span className="font-mono text-xs text-primary/35">0{index + 1}</span><div><h3 className="font-display text-xl font-bold uppercase">{item.name}</h3><p className="mt-1 text-sm text-primary/60">{item.description}</p></div></div><div className="flex items-center gap-3"><span className="font-mono text-sm font-bold">{money(item.price)}</span><button onClick={() => addToCart(item)} className="flex h-11 w-11 items-center justify-center bg-accent text-primary" aria-label={`Adicionar ${item.name}`}><Plus size={18}/></button></div></div>)}</div></div></section>

    <section id="local" className="border-t border-primary/10 bg-cream px-5 py-14 md:px-10 md:py-24"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-berry">05 · sem complicar</p><h2 className="font-display text-6xl font-bold leading-[.86] tracking-[-.07em] text-primary">COMO<br/>PEDIR.</h2><div className="mt-9 space-y-6">{[['01', 'MONTA', 'Escolhe tamanho e complementos.'], ['02', 'CONFERE', 'Revê o pedido e quantidades.'], ['03', 'PEDE', 'Continua pelo canal de pedidos da loja.']].map(([number, title, text]) => <div key={number} className="flex gap-5 border-t border-primary/15 pt-4"><span className="font-mono text-xs text-berry">{number}</span><div><h3 className="font-display text-xl font-bold text-primary">{title}</h3><p className="mt-1 text-sm text-primary/65">{text}</p></div></div>)}</div></div><div className="flex flex-col justify-end bg-primary p-7 text-primary-foreground md:p-10"><p className="font-mono text-[10px] uppercase tracking-[.3em] text-accent">onde encontrar</p><h3 className="mt-8 font-display text-5xl font-bold leading-[.88]">PELOTAS<br/><span className="text-accent">— RS</span></h3><div className="mt-14 border-t border-primary-foreground/20 pt-5"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary-foreground/55">Informações demonstrativas</p><p className="mt-3 font-display text-2xl font-bold">18H — 23H</p></div></div></div></section>

    <section className="relative overflow-hidden bg-berry px-5 py-14 text-primary md:px-10 md:py-24"><div className="absolute inset-y-0 right-0 hidden w-2/5 md:block"><Image src="/images/acai-bowl.png" alt="Açaí servido em bowl" fill className="object-cover opacity-80" sizes="40vw"/></div><div className="relative mx-auto flex max-w-7xl flex-col items-start gap-8 md:w-3/5 md:mr-auto"><h2 className="font-display text-7xl font-bold leading-[.82] tracking-[-.07em] md:text-9xl">JÁ SABE<br/>O QUE VAI?</h2><button onClick={() => setDrawer(true)} className="inline-flex min-h-14 items-center gap-4 bg-primary px-6 text-xs font-bold uppercase tracking-wider text-primary-foreground">Fazer pedido <ArrowUpRight size={17}/></button></div></section>
    <footer className="bg-primary px-5 py-8 text-primary-foreground md:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><div className="font-display text-xl font-bold">ROXO 53</div><div className="mt-1 font-mono text-[9px] tracking-[.24em] text-primary-foreground/60">AÇAÍ & BOWLS</div></div><p className="max-w-sm text-xs leading-relaxed text-primary-foreground/55">Projeto demonstrativo. Marca, produtos, preços, fotos, horários e canais de pedido são personalizados para cada negócio.</p><p className="font-mono text-[9px] uppercase tracking-[.2em] text-primary-foreground/40">Desenvolvido por Yagho</p></div></footer>

    {showMobileBar && <div className="fixed inset-x-0 bottom-0 z-30 px-4 pb-[calc(1rem+env(safe-area-inset-bottom))] lg:hidden"><div className="flex items-center justify-between bg-primary px-4 py-3 text-primary-foreground shadow-xl"><span className="font-mono text-[10px] uppercase tracking-[.18em]">{totalItems ? `${totalItems} item(ns)` : 'pronto para pedir?'}</span><button onClick={() => setDrawer(true)} className="flex min-h-11 items-center gap-2 bg-accent px-4 text-xs font-bold uppercase text-primary"><ShoppingBag size={16}/> Pedir</button></div></div>}
    {drawer && <CartDrawer cart={cart} total={cartTotal} changeQuantity={changeQuantity} close={() => setDrawer(false)} onAdd={() => { setDrawer(false); document.getElementById('monte')?.scrollIntoView({ behavior: 'smooth' }) }}/>} 
  </main>
}

function ComboCard({ product, onAdd, large = false }: { product: Product; onAdd: () => void; large?: boolean }) { return <article className={`relative overflow-hidden bg-primary text-primary-foreground ${large ? 'min-h-[23rem] md:min-h-[34rem]' : 'min-h-[18rem] md:min-h-[25rem]'}`}><Image src={product.image!} alt={product.name} fill className="object-cover opacity-80" sizes={large ? '(max-width: 768px) 100vw, 60vw' : '(max-width: 768px) 100vw, 40vw'}/><div className="absolute inset-0 bg-primary/35"/><div className="relative flex h-full min-h-[inherit] flex-col justify-end p-5 md:p-7"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">{product.description}</p><h3 className="mt-2 font-display text-4xl font-bold uppercase leading-none md:text-6xl">{product.name}</h3></div><div className="text-right"><p className="font-mono text-lg text-accent">{money(product.price)}</p><button onClick={onAdd} className="mt-3 flex h-11 w-11 items-center justify-center bg-accent text-primary" aria-label={`Adicionar ${product.name}`}><Plus size={18}/></button></div></div></div></article> }
function OptionGroup({ title, step, children }: { title: string; step: string; children: React.ReactNode }) { return <div><div className="mb-3 flex items-center gap-3"><span className="font-mono text-[10px] text-berry">{step}</span><h3 className="font-display text-xl font-bold text-primary">{title}</h3></div>{children}</div> }
function ChoiceList({ items, selected, toggle }: { items: Option[]; selected: Option[]; toggle: (item: Option) => void }) { return <div className="flex flex-wrap gap-2">{items.map(item => { const active = selected.some(current => current.name === item.name); return <button key={item.name} onClick={() => toggle(item)} className={`inline-flex min-h-11 items-center gap-2 border px-3 text-sm ${active ? 'border-berry bg-berry text-primary' : 'border-primary/20 text-primary'}`}>{active && <Check size={14}/>}<span>{item.name}</span>{item.extra > 0 && <small className="font-mono text-[10px]">+ {money(item.extra)}</small>}</button>})}</div> }
function CartDrawer({ cart, total, changeQuantity, close, onAdd }: { cart: CartItem[]; total: number; changeQuantity: (id: string, amount: number) => void; close: () => void; onAdd: () => void }) {
  return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-primary/50" onClick={close} aria-label="Fechar pedido"/><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-cream text-primary shadow-2xl"><div className="flex items-center justify-between border-b border-primary/15 px-5 py-5"><button onClick={close} className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider"><ChevronDown className="rotate-90" size={16}/> Voltar</button><span className="font-mono text-[10px] uppercase tracking-[.2em]">Seu pedido</span></div><div className="flex-1 overflow-y-auto px-5 py-6">{cart.length === 0 ? <div className="flex h-full flex-col items-center justify-center text-center"><ShoppingBag className="mb-5 text-berry" size={30}/><h3 className="font-display text-3xl font-bold">Ainda está vazio.</h3><p className="mt-3 max-w-xs text-sm text-primary/60">Monta teu açaí ou escolhe um dos favoritos da casa.</p><button onClick={onAdd} className="mt-6 bg-primary px-5 py-3 text-xs font-bold uppercase tracking-wider text-primary-foreground">Montar agora</button></div> : <div className="space-y-5">{cart.map(item => <div key={item.id} className="border-b border-primary/10 pb-5"><div className="flex justify-between gap-2"><h3 className="font-display text-lg font-bold uppercase">{item.name}</h3><button onClick={() => changeQuantity(item.id, -item.quantity)} aria-label={`Remover ${item.name}`}><X size={15}/></button></div><p className="mt-1 text-xs text-primary/55">{money(item.price)}</p><div className="mt-3 flex items-center gap-3"><button onClick={() => changeQuantity(item.id, -1)} className="flex h-8 w-8 items-center justify-center border border-primary/20"><Minus size={14}/></button><span className="font-mono text-sm">{item.quantity}</span><button onClick={() => changeQuantity(item.id, 1)} className="flex h-8 w-8 items-center justify-center bg-accent"><Plus size={14}/></button></div></div>)}</div>}</div>{cart.length > 0 && <div className="border-t border-primary/15 p-5"><div className="flex items-center justify-between"><span className="font-mono text-xs uppercase tracking-wider">Total</span><strong className="font-display text-3xl">{money(total)}</strong></div><button onClick={() => alert('Fluxo demonstrativo: conecte este botão ao canal de pedidos da loja.')} className="mt-5 min-h-13 w-full bg-primary text-xs font-bold uppercase tracking-wider text-primary-foreground">Finalizar pedido</button></div>}</aside></div>
}
